# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build-and-test:
    # These next lines define a Docker executor: https://circleci.com/docs/2.0/executor-types/
    # You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # Be sure to update the Docker image tag below to openjdk version of your application.
    # A list of available CircleCI Docker Convenience Images are available here: https://circleci.com/developer/images/image/cimg/openjdk
    docker:
      - image: cimg/openjdk:11.0
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          name: Collecting Maven wrapper
          command: mvn io.takari:maven:wrapper
      - run:
          name: Build API
          command: cd demo-contract-api && mvn -B -DskipTests clean install && cd ..
      - run:
          name: Build Server
          command: cd demo-contract-server && mvnw verify && cd ..
      - run:
          name: Adding stubs to local Maven repository
          command: cd demo-contract-server && mvnw org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file && cd ..
      - run:
          name: Build Client
          command: cd demo-contract-client && mvnw verify && cd ..

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  demo-contract: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-test
